# Generated by Django 5.1.4 on 2025-03-16 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expensetracker",
            old_name="money",
            new_name="wallet",
        ),
        migrations.AddField(
            model_name="money",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
